#!/bin/bash
# WSL LazyGit wrapper to fix TTY issues

# Set proper terminal environment
export TERM=xterm-256color

# Check if we have a proper TTY, if not create one
if [ ! -t 0 ]; then
    # If no TTY, try to run in a proper terminal session
    exec script -qec "lazygit $*" /dev/null
else
    # If we have TTY, run normally
    exec lazygit "$@"
fi